import type { NextRequest } from "next/server";
import { supabaseRest } from "@/lib/db/supabase-rest";
import { normalizeSteps, type WorkflowStep } from "@/lib/automation-workflows";
const q=(p:Record<string,string>)=>"?"+new URLSearchParams(p).toString();
const mapW=(r:any)=>({id:r.id,workspaceId:r.workspace_id,name:r.name,description:r.description??"",status:r.status,triggerType:r.trigger_type,schedule:r.schedule??undefined,steps:normalizeSteps(r.steps),lastRunAt:r.last_run_at??undefined,nextRunAt:r.next_run_at??undefined,createdAt:r.created_at,updatedAt:r.updated_at});
const mapR=(r:any)=>({id:r.id,workflowId:r.workflow_id,workspaceId:r.workspace_id,status:r.status,input:r.input??{},results:r.results??[],error:r.error??undefined,startedAt:r.started_at??undefined,finishedAt:r.finished_at??undefined,createdAt:r.created_at});
export async function listWorkflows(ctx:{req:NextRequest;workspaceId:string}){const rows=await supabaseRest<any[]>(ctx.req,"automation_workflows",{},q({workspace_id:`eq.${ctx.workspaceId}`,order:"created_at.desc"}));return rows.map(mapW);}
export async function getWorkflow(ctx:{req:NextRequest;workspaceId:string},id:string){const rows=await supabaseRest<any[]>(ctx.req,"automation_workflows",{},q({workspace_id:`eq.${ctx.workspaceId}`,id:`eq.${id}`,limit:"1"}));return rows[0]?mapW(rows[0]):null;}
export async function createWorkflow(ctx:{req:NextRequest;workspaceId:string},input:{name:string;description?:string;status?:string;triggerType:string;schedule?:string;steps:WorkflowStep[];createdBy?:string}){const [row]=await supabaseRest<any[]>(ctx.req,"automation_workflows",{method:"POST",body:JSON.stringify({workspace_id:ctx.workspaceId,name:input.name,description:input.description||null,status:input.status||"active",trigger_type:input.triggerType,schedule:input.schedule||null,steps:input.steps,created_by:input.createdBy||null}),headers:{Prefer:"return=representation"}});return mapW(row);}
export async function updateWorkflow(ctx:{req:NextRequest;workspaceId:string},id:string,input:Partial<{name:string;description:string;status:string;triggerType:string;schedule:string;steps:WorkflowStep[]}>){const body:any={};if(input.name!==undefined)body.name=input.name;if(input.description!==undefined)body.description=input.description;if(input.status!==undefined)body.status=input.status;if(input.triggerType!==undefined)body.trigger_type=input.triggerType;if(input.schedule!==undefined)body.schedule=input.schedule;if(input.steps!==undefined)body.steps=input.steps;body.updated_at=new Date().toISOString();const [row]=await supabaseRest<any[]>(ctx.req,"automation_workflows",{method:"PATCH",body:JSON.stringify(body),headers:{Prefer:"return=representation"}},q({workspace_id:`eq.${ctx.workspaceId}`,id:`eq.${id}`}));return row?mapW(row):null;}
export async function createRun(ctx:{req:NextRequest;workspaceId:string},input:{workflowId:string;input?:Record<string,unknown>;createdBy?:string}){const [row]=await supabaseRest<any[]>(ctx.req,"automation_runs",{method:"POST",body:JSON.stringify({workspace_id:ctx.workspaceId,workflow_id:input.workflowId,status:"queued",input:input.input||{},created_by:input.createdBy||null}),headers:{Prefer:"return=representation"}});return mapR(row);}
export async function listRuns(ctx:{req:NextRequest;workspaceId:string},workflowId?:string){const p:any={workspace_id:`eq.${ctx.workspaceId}`,order:"created_at.desc",limit:"50"};if(workflowId)p.workflow_id=`eq.${workflowId}`;const rows=await supabaseRest<any[]>(ctx.req,"automation_runs",{},q(p));return rows.map(mapR);}
export async function updateRun(ctx:{req:NextRequest;workspaceId:string},id:string,input:{status:string;results?:unknown[];error?:string}){const [row]=await supabaseRest<any[]>(ctx.req,"automation_runs",{method:"PATCH",body:JSON.stringify({status:input.status,results:input.results||[],error:input.error||null,started_at:input.status==="running"?new Date().toISOString():undefined,finished_at:["succeeded","failed","cancelled"].includes(input.status)?new Date().toISOString():undefined}),headers:{Prefer:"return=representation"}},q({workspace_id:`eq.${ctx.workspaceId}`,id:`eq.${id}`}));return row?mapR(row):null;}
